### ISSUE TITLE
Platform not loading on HA 2024.1.3

### ISSUE THREAD

**Issue by colinjgibbs** [hardbyte/ha-evnex#25]
Have just upgraded HA core to 2024.1.3. I now get this in the logs and no sensors are available (everything else seems to have loaded OK):
Logger: homeassistant.loader
Source: loader.py:842
First occurred: 19:06:42 (3 occurrences)
Last logged: 19:06:42

Unexpected exception importing platform custom_components.evnex.sensor
Unexpected exception importing platform custom_components.evnex.switch
Unexpected exception importing platform custom_components.evnex.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/evnex/sensor.py", line 29, in <module>
    from .entity import EvnexChargePointConnectorEntity, EvnexOrgEntity, EvnexChargerEntity
  File "/config/custom_components/evnex/entity.py", line 17, in <module>
    class EvnexOrgEntity(CoordinatorEntity):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 408, in __init__
    wrap_attr(cls, property_name)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 380, in wrap_attr
    raise TypeError(f"Can't override {attr_name} in subclass")
TypeError: Can't override _attr_unique_id in subclass

**Comment by colinjgibbs** [comment]
Have tried reloading evnex and also a restart of  HA but error remains.

**Comment by colinjgibbs** [comment]
Downgraded to 2024.1.2 and evnex loads OK.  Looks like some issue with 2024.1.3?

**Comment by xxxarmitagexx** [comment]
Same thing for me, none of the sensors were loading for my Evnex integration.
I tried to remove it and readd it and now it won’t even load the Charger... 

![Uploading image.png…]()
