### ISSUE TITLE
Evnex charger not available in 2024.6

### ISSUE THREAD

**Issue by sydney2711** [hardbyte/ha-evnex#36]
Hello

2024.5.5 and the charger was working fine
2024.6 and I get this error log:

This error originated from a custom integration.

###############
Logger: custom_components.evnex
Source: custom_components/evnex/__init__.py:185
integration: Evnex EV Charger (documentation, issues)
First occurred: 09:53:27 (5 occurrences)
Last logged: 09:54:40

Unhandled exception while updating evnex info
Traceback (most recent call last):
  File "/config/custom_components/evnex/__init__.py", line 185, in async_update_data
    for connector_brief in charge_point_detail.connectors:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'connectors'

#################

I hope there is a way to fix this issue because the charger is one of my most important device in home assistant.

**Comment by colinjgibbs** [comment]
Exactly  the same issue here. Was fine on 2024.5 versions.

**Comment by drc38** [comment]
I expect the root cause are the HA warnings associated with blocking calls inside the event loop such as:
`with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf:`

**Comment by colinjgibbs** [comment]
Happy to test if you would like me to.

**Comment by The-Organist** [comment]
Somewhat novice, but does this pull request mean that we don’t have to individually do anything - it just fixes at some point?

**Comment by colinjgibbs** [comment]
@The-Organist  - typically a pull request is asking for collaborators on the code (in this case hardbyte) to review and comment on the changes.  Highly likely this will fix the problem when released.

**Comment by sydney2711** [comment]
Just updated core to 2024.6.2 
I get basically the same error just the name of the python file that causes the problem has changed

####################

**Comment by The-Organist** [comment]
after EVNEX package update installed:

Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 6:51:23 AM (3 occurrences)
Last logged: 6:51:39 AM

Unable to install package evnex>=0.4.1: ERROR: Cannot install evnex==0.4.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by drc38** [comment]
If you stick with pydantic v1 (HA default) and downgrade to evnex v0.5.3 then you should be fine. Other option is to force install pydantic v2 and use v0.6 pre-releases but other integrations may have problems if they still use v1

**Comment by sultanoswing** [comment]
> then you should be fine.

Nope. Downgraded to 0.53 (by pulling the code then copying across to my HA's custom_components folder using WinSCP). The integration starts, asks for my Evnex login, which appears successful (my real name pops up), but it still fails to start. The logs now show:

`Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 12:22:15 (24 occurrences)
Last logged: 12:27:36

Detected blocking call to open inside the event loop by custom integration 'evnex' at custom_components/evnex/__init__.py, line 55: with open(file, "r") as spf: (offender: /config/custom_components/evnex/__init__.py, line 55: with open(file, "r") as spf:), please create a bug report at https://github.com/hardbyte/ha-evnex/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 572, in _async_handle_step result = await self.async_finish_flow(flow, result.copy()) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1403, in async_finish_flow await self.config_entries.async_add(entry) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1708, in async_add await self.async_setup(entry.entry_id) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1819, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/evnex/__init__.py", line 263, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/evnex/__init__.py", line 150, in async_update_data persist_evnex_auth_tokens( File "/config/custom_components/evnex/__init__.py", line 55, in persist_evnex_auth_tokens with open(file, "r") as spf:
Detected blocking call to open inside the event loop by custom integration 'evnex' at custom_components/evnex/__init__.py, line 67: with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf: (offender: /config/custom_components/evnex/__init__.py, line 67: with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf:), please create a bug report at https://github.com/hardbyte/ha-evnex/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 572, in _async_handle_step result = await self.async_finish_flow(flow, result.copy()) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1403, in async_finish_flow await self.config_entries.async_add(entry) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1708, in async_add await self.async_setup(entry.entry_id) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1819, in async_setup await entry.async_setup(self.hass) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/evnex/__init__.py", line 263, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/evnex/__init__.py", line 150, in async_update_data persist_evnex_auth_tokens( File "/config/custom_components/evnex/__init__.py", line 67, in persist_evnex_auth_tokens with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf:
Detected blocking call to open inside the event loop by custom integration 'evnex' at custom_components/evnex/__init__.py, line 78: with open(file, "r") as spf: (offender: /config/custom_components/evnex/__init__.py, line 78: with open(file, "r") as spf:), please create a bug report at https://github.com/hardbyte/ha-evnex/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1510, in _run_async_call_action hass.async_run_hass_job(job, time_tracker_utcnow()) File "/usr/src/homeassistant/homeassistant/core.py", line 936, in async_run_hass_job hassjob.target(*args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 720, in _async_setup_again hass.async_create_background_task( File "/usr/src/homeassistant/homeassistant/core.py", line 860, in async_create_background_task task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/evnex/__init__.py", line 104, in async_setup_entry evnex_auth_tokens = retrieve_evnex_auth_tokens(hass, entry) File "/config/custom_components/evnex/__init__.py", line 78, in retrieve_evnex_auth_tokens with open(file, "r") as spf:
Detected blocking call to open inside the event loop by custom integration 'evnex' at custom_components/evnex/__init__.py, line 55: with open(file, "r") as spf: (offender: /config/custom_components/evnex/__init__.py, line 55: with open(file, "r") as spf:), please create a bug report at https://github.com/hardbyte/ha-evnex/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/evnex/__init__.py", line 263, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/evnex/__init__.py", line 150, in async_update_data persist_evnex_auth_tokens( File "/config/custom_components/evnex/__init__.py", line 55, in persist_evnex_auth_tokens with open(file, "r") as spf:
Detected blocking call to open inside the event loop by custom integration 'evnex' at custom_components/evnex/__init__.py, line 67: with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf: (offender: /config/custom_components/evnex/__init__.py, line 67: with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf:), please create a bug report at https://github.com/hardbyte/ha-evnex/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/evnex/__init__.py", line 263, in async_setup_entry await coordinator.async_config_entry_first_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 277, in async_config_entry_first_refresh await self._async_refresh( File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_update_data return await self.update_method() File "/config/custom_components/evnex/__init__.py", line 150, in async_update_data persist_evnex_auth_tokens( File "/config/custom_components/evnex/__init__.py", line 67, in persist_evnex_auth_tokens with open(os.open(file, os.O_CREAT | os.O_WRONLY, 0o600), "w") as spf:`

**Comment by drc38** [comment]
You can include https://github.com/hardbyte/ha-evnex/commit/623b9da56c1317da93e1fdfc2317f3c202acb8c4 to get rid of blocking errors. But the warnings should not prevent hhe integration working.

**Comment by sultanoswing** [comment]
Thanks - that update got rid of those errors, now just the previous:

`Logger: custom_components.evnex
Source: custom_components/evnex/__init__.py:186
integration: Evnex EV Charger ([documentation](https://github.com/hardbyte/ha-evnex), [issues](https://github.com/hardbyte/ha-evnex/issues))
First occurred: 13:42:30 (3 occurrences)
Last logged: 13:43:00

Unhandled exception while updating evnex info
Traceback (most recent call last):
  File "/config/custom_components/evnex/__init__.py", line 186, in async_update_data
    for connector_brief in charge_point_detail.connectors:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'connectors'`

**Comment by drc38** [comment]
Pull a fresh HA image, the pydantic versions may have got messed up or make these changes https://github.com/hardbyte/ha-evnex/pull/38

**Comment by sultanoswing** [comment]
> Pull a fresh HA

Since I run HAOSS in a VM, it's a little more involved....but yes, I may look at doing that. At least with HAOSS you can restore from a backup file.

**Comment by colinjgibbs** [comment]
Have made the changes as per [#38](https://github.com/hardbyte/ha-evnex/pull/38) and all working now.  I'm on a RPi 4:
Core
2024.6.4
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240610.1

**Comment by zurnaik** [comment]
Having the same error as the originally reported issue on 0.5.3. Integration configuration successfully authenticates to Evnex then retries indefinitely due to this unhandled exception with or without the patch #38. I can't test 0.6.x because a 500 Internal Server Error pops up instead of the Evnex username / password prompt.

I am running
Home Assistant: 12.3
Home Assistant Core: 2024.7

Unhandled exception while updating evnex info
Traceback (most recent call last):
File "/config/custom_components/evnex/init.py", line 185, in async_update_data
for connector_brief in charge_point_detail.connectors:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'connectors'

################

**Comment by hardbyte** [comment]
What version of Pydantic does your system have @zurnaik?

**Comment by zurnaik** [comment]
> What version of Pydantic does your system have @zurnaik?

pydantic                         1.10.17
pydantic_core                    2.20.1

**Comment by glasody** [comment]
I have found a simple fix for those that are still using pydantic v1.
Just replace [these lines (L181-183) inside \_\_init\_\_.py](https://github.com/hardbyte/ha-evnex/blob/917e69531c616ef69aa93cb03f22d8edb0f2db52/custom_components/evnex/__init__.py#L181-L183) with the below code then restart homeassistant.
``` python
charge_point_detail = EvnexChargePointDetail(
    **api_v3_response.data.attributes
)
```
I'm not a python developer so wasn't sure if this code is compatible with the latest versions of pydantic so I didn't submit a PR.
Hope this helps others out there like me

**Comment by The-Organist** [comment]
This worked a treat, thank you.  Now gave control back again.  Hopefully this is not something I have to adjust every time an update downloads?

**Comment by zlodag** [comment]
It looks like Home Assistant Core is updating to Pydantic v2 in version [2025.1](https://github.com/home-assistant/developers.home-assistant/pull/2492), and the update is currently on the [dev channel](https://github.com/home-assistant/core/pull/131963). Switching to the dev channel solved this issue for me, v0.6.0 of this integration loads successfully.

If the integration is already configured, this should work while waiting for HA core 2025.1 to be released in the stable channel. Note the dev channel is not stable so other things may break...
```
ha supervisor options --channel dev
ha supervisor reload
ha core update
```

To switch back to the stable channel:

```
ha supervisor options --channel stable
```

I didn't have a configuration set up, and I couldn't get the add integration wizard to load when I had upgraded HA Core to dev (probably an unrelated issue) so I reverted HA to the stable version: ```ha core update --version 2024.12.3```, reverted to v0.5.3 of this integration  (HACS > evnex > "Redownload" > v0.5.3), followed the prompt to restart HA, configured the integration, upgraded the evnex integration to v0.6.0, then repeated the first step to upgrade HA to dev version.
